import {ETHER} from "./utils";
import {ethers} from "ethers";

export const TEST_VOLUMES = [
    ethers.utils.parseEther("0.001"),
    ethers.utils.parseEther("0.01"),
    ethers.utils.parseEther("0.1"),
    ethers.utils.parseEther("0.2"),
    ethers.utils.parseEther("0.3"),
    ethers.utils.parseEther("0.4"),
    ethers.utils.parseEther("0.5"),
    ethers.utils.parseEther("0.6"),
    ethers.utils.parseEther("0.7"),
    ethers.utils.parseEther("0.8"),
    ethers.utils.parseEther("0.9"),
    ethers.utils.parseEther("1.0"),
    ethers.utils.parseEther("1.1"),
    ethers.utils.parseEther("1.2"),
    ethers.utils.parseEther("1.3"),
    ethers.utils.parseEther("1.4"),
    ethers.utils.parseEther("1.5"),
    ethers.utils.parseEther("1.6"),
    ethers.utils.parseEther("1.7"),
    ethers.utils.parseEther("1.8"),
    ethers.utils.parseEther("1.9"),
    ethers.utils.parseEther("2.0"),
    ethers.utils.parseEther("2.1"),
    ethers.utils.parseEther("2.2"),
    ethers.utils.parseEther("2.3"),
    ethers.utils.parseEther("2.4"),
    ethers.utils.parseEther("2.5"),
    ethers.utils.parseEther("2.6"),
    ethers.utils.parseEther("2.7"),
    ethers.utils.parseEther("2.8"),
    ethers.utils.parseEther("2.9"),
    ethers.utils.parseEther("3.0"),
    ethers.utils.parseEther("3.1"),
    ethers.utils.parseEther("3.2"),
    ethers.utils.parseEther("3.3"),
    ethers.utils.parseEther("3.4"),
    ethers.utils.parseEther("3.5"),
    ethers.utils.parseEther("3.6"),
    ethers.utils.parseEther("3.7"),
    ethers.utils.parseEther("3.8"),
    ethers.utils.parseEther("3.9"),
    ethers.utils.parseEther("4.0"),
    ethers.utils.parseEther("4.1"),
];


export const TEST_VOLUMES_REVERSED = TEST_VOLUMES.reverse();
